[package]
name = "from_file"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]

[dependencies]
serde = "1.0"
serde_yaml = "0.8"

serde_derive = "1.0"
serde_json = "1.0"

from_file_derive = { path = "../from_file_derive" }

[lib]
name = "from_file"
path = "src/lib.rs"
